# Generated by Django 6.0.3 on 2026-03-20 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('requestsystem', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='custom_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'custom_groups',
            },
        ),
        migrations.CreateModel(
            name='CustomGroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='communications.customgroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_group_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'custom_group_members',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('is_important', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='communications.message')),
                ('related_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='requestsystem.request')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'messages',
            },
        ),
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.URLField(max_length=2048)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='communications.message')),
            ],
            options={
                'db_table': 'message_attachments',
            },
        ),
        migrations.CreateModel(
            name='MessageRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('TO', 'To'), ('CC', 'Cc'), ('BCC', 'Bcc')], default='TO', max_length=10)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='communications.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_recipients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'message_recipients',
            },
        ),
        migrations.CreateModel(
            name='MessageTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('USER', 'User'), ('DEPARTMENT', 'Department'), ('GROUP', 'Group')], max_length=20)),
                ('target_id', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='communications.message')),
            ],
            options={
                'db_table': 'message_targets',
            },
        ),
        migrations.AddIndex(
            model_name='customgroup',
            index=models.Index(fields=['created_by'], name='custom_grou_created_1f139a_idx'),
        ),
        migrations.AddIndex(
            model_name='customgroup',
            index=models.Index(fields=['name'], name='custom_grou_name_7d3839_idx'),
        ),
        migrations.AddIndex(
            model_name='customgroupmember',
            index=models.Index(fields=['group'], name='custom_grou_group_i_51c6f1_idx'),
        ),
        migrations.AddIndex(
            model_name='customgroupmember',
            index=models.Index(fields=['user'], name='custom_grou_user_id_10ad3e_idx'),
        ),
        migrations.AddConstraint(
            model_name='customgroupmember',
            constraint=models.UniqueConstraint(fields=('group', 'user'), name='uniq_custom_group_member'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', 'created_at'], name='messages_sender__bf8b1c_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['related_request'], name='messages_related_bfd757_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['parent'], name='messages_parent__61f3f9_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['is_important'], name='messages_is_impo_a15e63_idx'),
        ),
        migrations.AddIndex(
            model_name='messageattachment',
            index=models.Index(fields=['message'], name='message_att_message_2a1fa5_idx'),
        ),
        migrations.AddIndex(
            model_name='messagerecipient',
            index=models.Index(fields=['message', 'type'], name='message_rec_message_1159fb_idx'),
        ),
        migrations.AddIndex(
            model_name='messagerecipient',
            index=models.Index(fields=['user', 'is_read'], name='message_rec_user_id_8ab693_idx'),
        ),
        migrations.AddIndex(
            model_name='messagerecipient',
            index=models.Index(fields=['read_at'], name='message_rec_read_at_65e0de_idx'),
        ),
        migrations.AddConstraint(
            model_name='messagerecipient',
            constraint=models.UniqueConstraint(fields=('message', 'user'), name='uniq_message_user_recipient'),
        ),
        migrations.AddIndex(
            model_name='messagetarget',
            index=models.Index(fields=['message'], name='message_tar_message_b6b559_idx'),
        ),
        migrations.AddIndex(
            model_name='messagetarget',
            index=models.Index(fields=['target_type', 'target_id'], name='message_tar_target__1f79b8_idx'),
        ),
    ]
