# Generated by Django 6.0.3 on 2026-03-22 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageattachment',
            name='file_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='messageattachment',
            name='file_size',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='messageattachment',
            name='mime_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
