# Generated by Django 6.0.3 on 2026-03-22 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_messageattachment_file_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagerecipient',
            name='is_important',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='messagerecipient',
            index=models.Index(fields=['user', 'is_important'], name='message_reci_user_id_5eca30_idx'),
        ),
    ]
