# Generated by Django 6.0.3 on 2026-03-20 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('approvals', '0001_initial'),
        ('requestsystem', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='requestapproval',
            name='approver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='request_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requestapproval',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='requestsystem.request'),
        ),
        migrations.AddIndex(
            model_name='workflow',
            index=models.Index(fields=['name'], name='workflows_name_5bf4ac_idx'),
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='approvals.workflow'),
        ),
        migrations.AddField(
            model_name='requestapproval',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='request_approvals', to='approvals.workflowstep'),
        ),
        migrations.AddIndex(
            model_name='workflowstep',
            index=models.Index(fields=['workflow', 'step_order'], name='workflow_st_workflo_f96da4_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowstep',
            index=models.Index(fields=['role_required'], name='workflow_st_role_re_3c0227_idx'),
        ),
        migrations.AddConstraint(
            model_name='workflowstep',
            constraint=models.UniqueConstraint(fields=('workflow', 'step_order'), name='uniq_workflow_step_order'),
        ),
        migrations.AddIndex(
            model_name='requestapproval',
            index=models.Index(fields=['request', 'status'], name='request_app_request_466981_idx'),
        ),
        migrations.AddIndex(
            model_name='requestapproval',
            index=models.Index(fields=['approver', 'status'], name='request_app_approve_09faf4_idx'),
        ),
        migrations.AddIndex(
            model_name='requestapproval',
            index=models.Index(fields=['step'], name='request_app_step_id_5195a2_idx'),
        ),
        migrations.AddConstraint(
            model_name='requestapproval',
            constraint=models.UniqueConstraint(fields=('request', 'step', 'approver'), name='uniq_request_approval_actor'),
        ),
    ]
