# Generated by Django 6.0.3 on 2026-03-21 08:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0002_initial'),
        ('requestsystem', '0004_request_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='workflow',
            name='type',
            field=models.CharField(choices=[('LEAVE', 'Leave'), ('PURCHASE', 'Purchase'), ('TASK', 'Task')], db_index=True, default='TASK', max_length=20),
        ),
        migrations.CreateModel(
            name='WorkflowInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_step', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], db_index=True, default='ACTIVE', max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_instance', to='requestsystem.request')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='approvals.workflow')),
            ],
            options={
                'db_table': 'workflow_instances',
                'indexes': [models.Index(fields=['status'], name='workflow_in_status_a4291a_idx'), models.Index(fields=['workflow', 'status'], name='workflow_in_workflo_e0bc84_idx')],
            },
        ),
    ]
