# Generated by Django 6.0.3 on 2026-03-23 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("approvals", "0003_workflow_description_workflow_type_workflowinstance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflow",
            name="type",
            field=models.CharField(
                choices=[
                    ("LEAVE", "Leave"),
                    ("PURCHASE", "Purchase"),
                    ("DOCUMENT", "Document"),
                    ("TASK", "Task"),
                ],
                db_index=True,
                default="TASK",
                max_length=20,
            ),
        ),
    ]
