# Generated by Django 6.0.3 on 2026-03-23 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0004_alter_workflow_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('LEAVE', 'Leave'), ('PURCHASE', 'Purchase'), ('DOCUMENT', 'Document')], db_index=True, max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('schema', models.JSONField(blank=True, default=list, help_text='Array of field definitions: {name, label, input, required, options}')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='templates', to='approvals.workflow')),
            ],
            options={
                'db_table': 'approval_templates',
                'indexes': [models.Index(fields=['type', 'is_active'], name='approval_te_type_6085f1_idx'), models.Index(fields=['workflow'], name='approval_te_workflo_6fe850_idx')],
                'constraints': [models.UniqueConstraint(fields=('type', 'name'), name='uniq_template_type_name')],
            },
        ),
    ]
