# Generated by Django 6.0.3 on 2026-03-23 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0005_approvaltemplate'),
        ('departments', '0003_department_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowstep',
            name='approver_department',
            field=models.ForeignKey(blank=True, help_text='Used when approver_scope=SPECIFIC_DEPT', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_steps', to='departments.department'),
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='approver_scope',
            field=models.CharField(choices=[('ALL_WITH_ROLE', 'Tất cả người dùng có vai trò'), ('DEPT_OF_REQUESTER', 'Quản lý phòng ban của người tạo'), ('SPECIFIC_DEPT', 'Quản lý của phòng ban cụ thể'), ('SPECIFIC_USER', 'Người dùng cụ thể')], default='ALL_WITH_ROLE', max_length=20),
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='approver_user',
            field=models.ForeignKey(blank=True, help_text='Used when approver_scope=SPECIFIC_USER', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designated_workflow_steps', to=settings.AUTH_USER_MODEL),
        ),
    ]
