# Generated by Django 4.2.7 on 2026-03-28 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(help_text='Internal device UID', unique=True)),
                ('user_id', models.CharField(help_text='User ID on device', max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('privilege', models.IntegerField(default=0)),
                ('group_id', models.CharField(blank=True, max_length=50)),
                ('card', models.BigIntegerField(default=0)),
                ('department', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Nhân viên',
                'verbose_name_plural': 'Nhân viên',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('success', 'Thành công'), ('failed', 'Thất bại'), ('partial', 'Một phần')], max_length=20)),
                ('records_synced', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Lịch sử đồng bộ',
                'verbose_name_plural': 'Lịch sử đồng bộ',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=50)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('status', models.IntegerField(default=0)),
                ('punch', models.IntegerField(choices=[(0, 'Vào ca'), (1, 'Ra ca'), (2, 'Nghỉ giải lao'), (3, 'Trở lại'), (4, 'Tăng ca vào'), (5, 'Tăng ca ra')], default=0)),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='attendance.employee')),
            ],
            options={
                'verbose_name': 'Bản ghi chấm công',
                'verbose_name_plural': 'Bản ghi chấm công',
                'ordering': ['-timestamp'],
                'unique_together': {('user_id', 'timestamp')},
            },
        ),
    ]
