# Generated by Django 6.0.3 on 2026-03-30 04:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('departments', '0003_department_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendancePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('monthly', 'Bảng công tháng'), ('logs', 'Lịch sử chấm công'), ('report', 'Báo cáo chấm công')], max_length=20)),
                ('can_view_all', models.BooleanField(default=False, help_text='Cho phép xem dữ liệu chấm công của tất cả nhân viên')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_permissions', to='departments.department')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Phân quyền chấm công',
                'verbose_name_plural': 'Phân quyền chấm công',
                'constraints': [models.CheckConstraint(condition=models.Q(('department__isnull', True), ('user__isnull', True), _negated=True), name='attendance_perm_user_or_dept')],
            },
        ),
    ]
