# Generated by Django 6.0.3 on 2026-03-30 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_employee_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_code',
            field=models.CharField(blank=True, help_text='Mã nhân viên', max_length=50, null=True),
        ),
    ]
