# Generated by Django 6.0.3 on 2026-03-30 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_employee_employee_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tên ca', max_length=100, unique=True)),
                ('shift_type', models.CharField(choices=[('hc', 'Ca hành chính (2 lần chấm)'), ('3punch', 'Ca 3 lần chấm'), ('4punch', 'Ca 4 lần chấm')], default='hc', max_length=10)),
                ('start_time', models.TimeField(help_text='Giờ bắt đầu ca')),
                ('end_time', models.TimeField(help_text='Giờ kết thúc ca')),
                ('mid_time', models.TimeField(blank=True, help_text='Giờ giữa ca (ca 3 lần)', null=True)),
                ('mid_time2', models.TimeField(blank=True, help_text='Giờ vào ca 2 (ca 4 lần)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ca làm việc',
                'verbose_name_plural': 'Ca làm việc',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='shift',
            field=models.ForeignKey(blank=True, help_text='Ca làm việc', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='attendance.workshift'),
        ),
    ]
