# Generated by Django 6.0.3 on 2026-03-30 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_workshift_employee_shift'),
    ]

    operations = [
        migrations.CreateModel(
            name='LateEarlyRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('late', 'Đi muộn'), ('early', 'Về sớm')], max_length=5)),
                ('from_minutes', models.PositiveIntegerField(help_text='Từ (phút)')),
                ('to_minutes', models.PositiveIntegerField(blank=True, help_text='Đến (phút), null = không giới hạn', null=True)),
                ('label', models.CharField(blank=True, help_text='Tên mốc, VD: Muộn 15-30p', max_length=100)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='late_early_rules', to='attendance.workshift')),
            ],
            options={
                'verbose_name': 'Quy tắc đi muộn / về sớm',
                'verbose_name_plural': 'Quy tắc đi muộn / về sớm',
                'ordering': ['shift', 'rule_type', 'from_minutes'],
            },
        ),
        migrations.CreateModel(
            name='PenaltyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('late', 'Đi muộn'), ('early', 'Về sớm')], max_length=5)),
                ('from_count', models.PositiveIntegerField(help_text='Từ lần thứ')),
                ('to_count', models.PositiveIntegerField(blank=True, help_text='Đến lần thứ, null = trở lên', null=True)),
                ('penalty_amount', models.PositiveIntegerField(default=0, help_text='Số tiền phạt (VNĐ)')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalty_configs', to='attendance.workshift')),
            ],
            options={
                'verbose_name': 'Cấu hình phạt đi muộn / về sớm',
                'verbose_name_plural': 'Cấu hình phạt đi muộn / về sớm',
                'ordering': ['shift', 'rule_type', 'from_count'],
            },
        ),
    ]
