# Generated by Django 6.0.3 on 2026-03-20 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('approvals', '0002_initial'),
        ('requestsystem', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='request',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='request',
            name='parent_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resubmitted_requests', to='requestsystem.request'),
        ),
        migrations.AddField(
            model_name='request',
            name='workflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='approvals.workflow'),
        ),
        migrations.AddField(
            model_name='rating',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='requestsystem.request'),
        ),
        migrations.AddField(
            model_name='requestassignment',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='requestsystem.request'),
        ),
        migrations.AddField(
            model_name='requestassignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='request_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requestlog',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='requestsystem.request'),
        ),
        migrations.AddField(
            model_name='requestlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['type', 'status'], name='requests_type_cb8a94_idx'),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['target_type', 'target_id'], name='requests_target__7d5e43_idx'),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['created_by'], name='requests_created_cd1604_idx'),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['deadline'], name='requests_deadlin_53ff0c_idx'),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['workflow', 'current_step'], name='requests_workflo_be01a1_idx'),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['created_at'], name='requests_created_4c1c4c_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['request'], name='ratings_request_7ce249_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['created_by'], name='ratings_created_237fb9_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['rating'], name='ratings_rating_105b29_idx'),
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.UniqueConstraint(fields=('request', 'created_by'), name='uniq_request_rating_by_user'),
        ),
        migrations.AddIndex(
            model_name='requestassignment',
            index=models.Index(fields=['request', 'status'], name='request_ass_request_2c1935_idx'),
        ),
        migrations.AddIndex(
            model_name='requestassignment',
            index=models.Index(fields=['user', 'status'], name='request_ass_user_id_8e49ff_idx'),
        ),
        migrations.AddIndex(
            model_name='requestassignment',
            index=models.Index(fields=['action_at'], name='request_ass_action__d7a77c_idx'),
        ),
        migrations.AddConstraint(
            model_name='requestassignment',
            constraint=models.UniqueConstraint(fields=('request', 'user'), name='uniq_request_assignment'),
        ),
        migrations.AddIndex(
            model_name='requestlog',
            index=models.Index(fields=['request', 'created_at'], name='request_log_request_7b02df_idx'),
        ),
        migrations.AddIndex(
            model_name='requestlog',
            index=models.Index(fields=['user'], name='request_log_user_id_26b09e_idx'),
        ),
        migrations.AddIndex(
            model_name='requestlog',
            index=models.Index(fields=['action'], name='request_log_action_adfa8e_idx'),
        ),
    ]
