# Generated by Django 6.0.3 on 2026-03-20 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestsystem', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestassignment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('CLOSED', 'Closed'), ('DONE', 'Done')], default='PENDING', max_length=20),
        ),
    ]
