# Generated by Django 6.0.3 on 2026-03-21 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestsystem', '0003_alter_requestassignment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='category',
            field=models.CharField(blank=True, choices=[('LEAVE', 'Leave'), ('PURCHASE', 'Purchase'), ('TASK', 'Task')], db_index=True, help_text='Used to auto-assign a matching workflow on creation.', max_length=20, null=True),
        ),
    ]
