# Generated by Django 6.0.3 on 2026-03-22 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestsystem', '0004_request_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='notes',
            field=models.TextField(blank=True, help_text='Rejection or failure reason visible to both sender and recipient'),
        ),
    ]
