# Generated by Django 6.0.3 on 2026-03-23 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requestsystem", "0005_request_notes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("LEAVE", "Leave"),
                    ("PURCHASE", "Purchase"),
                    ("DOCUMENT", "Document"),
                    ("TASK", "Task"),
                ],
                db_index=True,
                help_text="Used to auto-assign a matching workflow on creation.",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="request",
            name="form_data",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name="RequestAttachment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("file", models.FileField(upload_to="request_attachments/%Y/%m/%d")),
                ("file_name", models.CharField(blank=True, default="", max_length=255)),
                ("file_size", models.PositiveBigIntegerField(blank=True, null=True)),
                ("mime_type", models.CharField(blank=True, default="", max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="requestsystem.request",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="request_attachments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "request_attachments",
            },
        ),
        migrations.AddIndex(
            model_name="requestattachment",
            index=models.Index(fields=["request"], name="request_att_request_b7b303_idx"),
        ),
    ]
