# Generated by Django 6.0.3 on 2026-03-27 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestsystem', '0006_request_form_data_requestattachment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestQuickTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description/hint shown to users')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'request_quick_titles',
                'ordering': ['sort_order', 'title'],
            },
        ),
    ]
