# Generated by Django 6.0.3 on 2026-03-21 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_department_user_full_name'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='users_role_0ace22_idx',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
