# Generated by Django 6.0.3 on 2026-03-30 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendancepermission'),
        ('users', '0004_backfill_rbac_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='attendance_employee',
            field=models.OneToOneField(blank=True, help_text='Liên kết với nhân viên trên máy chấm công', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_user', to='attendance.employee'),
        ),
    ]
