# Generated by Django 6.0.3 on 2026-03-30 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_attendance_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='employee_code',
            field=models.CharField(blank=True, help_text='Mã nhân viên', max_length=50, null=True, unique=True),
        ),
    ]
